# Amazon account
email: "email"
password: "pass"

# product ASINS (one asin = one task)
asins: ["B08GYKNCCP"]

# delay for the monitor in seconds
monitordelay: 5

#monitor proxies. recommended one task = one proxy (["url:port:user:pw",...])
proxy : []

#price limits
maxprice: 500

# discord webhook for success
webhook: "webhook"

#headless option (True / False) (leave browser open)
headless: True