# Amazon account
email: "email"
password: "password"

# product ASINS (one asin = one task)
asins: ["",""]

# delay for the monitor in seconds
monitordelay: 5

#monitor proxies. recommended one task = one proxy (["url:port:user:pw",...])
proxy : []

#price limits
maxprice: 1000

# discord webhook for success
webhook: "none"

#discord ID for ping
discord: "missingid"

#headless option (True / False) (leave browser open)
headless: True