name: Release Zipfile with PyInstaller

on:
  push:
    branches: [ master ]
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Release') }}

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: papeloto/action-zip@v1
      with:
        files: src/dist/windows
        dest: warehouse.zip
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/warehouse.zip
        tag_name: Release-${{ github.run_id }}
        body: "- Download the warehouse.zip file\n- Fill in the config.yaml\n- Start run.exe\n\nChanges:\n ${{ github.event.head_commit.message }}"
